import { useCallback, useEffect, useState } from "react";
import { Check, CheckCircle2, Clock3, LogOut, PackageCheck, RefreshCw, ShieldCheck, UserRound, X, XCircle } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";
import { approveClaim, getPendingClaims, rejectClaim } from "../services/api";
import "../App.css";

export default function Admin(){
 const {user,logout}=useAuth();const {showToast}=useToast();const [claims,setClaims]=useState([]),[loading,setLoading]=useState(true),[processingId,setProcessingId]=useState(null);
 const loadClaims=useCallback(async()=>{try{setLoading(true);const data=await getPendingClaims();setClaims(data.claims||[]);}catch(err){showToast(err.message,"error");}finally{setLoading(false);}},[showToast]);
 useEffect(()=>{loadClaims();},[loadClaims]);
 const approve=async(id)=>{if(!window.confirm("Approve this claim? The item will be marked as claimed and other pending claims for it will be rejected."))return;try{setProcessingId(id);const data=await approveClaim(id);showToast(data.message||"Claim approved successfully!");await loadClaims();}catch(err){showToast(err.message,"error");}finally{setProcessingId(null);}};
 const reject=async(id)=>{if(!window.confirm("Reject this claim request?"))return;try{setProcessingId(id);const data=await rejectClaim(id);showToast(data.message||"Claim rejected successfully.","info");await loadClaims();}catch(err){showToast(err.message,"error");}finally{setProcessingId(null);}};
 return <div className="app-shell"><header className="topbar"><div className="container topbar-inner"><div className="brand"><div className="brand-mark"><ShieldCheck size={20}/></div><div>Lost &amp; Found<small>Administrator console</small></div></div><div className="user-actions"><div className="user-chip"><div className="avatar">{user?.name?.[0]?.toUpperCase()||"A"}</div><span>{user?.name}</span></div><button className="btn btn-secondary icon-btn" onClick={()=>{logout();showToast("You have been logged out.","info");}} title="Logout"><LogOut size={17}/></button></div></div></header>
 <main className="page container"><div className="hero-row"><div><span className="eyebrow"><ShieldCheck size={14}/> Admin verification</span><h1 className="title">Claim review center</h1><p className="subtitle">Review ownership evidence submitted by users and make the final verification decision.</p></div><button className="btn btn-secondary" onClick={loadClaims} disabled={loading}><RefreshCw className={loading?"spinner":""} size={17}/> Refresh</button></div>
 <div className="admin-stats"><div className="stat-card"><div className="stat-top"><span>Pending claims</span><Clock3 size={17}/></div><span className="stat-value">{claims.length}</span></div><div className="stat-card"><div className="stat-top"><span>Verification</span><ShieldCheck size={17}/></div><span className="stat-value">Manual</span></div><div className="stat-card"><div className="stat-top"><span>Queue status</span><PackageCheck size={17}/></div><span className="stat-value" style={{fontSize:21}}>{claims.length?"Needs review":"All clear"}</span></div></div>
 <div className="form-header" style={{marginBottom:18}}><div><h2 className="section-title">Pending claim requests</h2><p className="section-note">Approve only when the submitted proof is convincing.</p></div></div>
 {loading?<div className="empty"><RefreshCw className="spinner" size={28}/><p>Loading claim requests…</p></div>:claims.length===0?<div className="empty"><div className="empty-icon"><CheckCircle2 size={26}/></div><h3>No pending claims</h3><p>Everything has been reviewed. Nice work.</p></div>:<div className="claim-grid">{claims.map(claim=>{const item=claim.foundItem, claimant=claim.claimant, processing=processingId===claim._id;return <article className="claim-card" key={claim._id}>{item?.image?<img src={item.image} alt={item?.name||"Found item"}/>:<div className="image-placeholder"><PackageCheck size={44}/></div>}<div className="claim-card-body"><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start"}}><div><h3 className="item-title">{item?.name||"Unknown item"}</h3><div className="meta">{item?.category||"-"} · {item?.location||"-"}</div></div><span className="badge badge-available">pending</span></div><div className="claim-section"><div className="claim-label">Claimant</div><p className="claim-value"><strong>{claimant?.name||"-"}</strong><br/>{claimant?.email||"-"}<br/>{claimant?.phone||"-"}</p></div><div className="claim-section"><div className="claim-label">Ownership proof</div><div className="reason">{claim.reason}</div></div><div className="action-row"><button className="btn btn-success" onClick={()=>approve(claim._id)} disabled={processing}>{processing?<RefreshCw className="spinner" size={16}/>:<Check size={17}/>} {processing?"Processing…":"Approve"}</button><button className="btn btn-danger" onClick={()=>reject(claim._id)} disabled={processing}><X size={17}/> Reject</button></div></div></article>})}</div>}
 </main></div>;
}
